db:
  image: postgres:9.4.1
  ports:
    - "5444:5432"
  volumes_from:
    - dbdata
  container_name: postgres-db

dbdata:
  image: postgres:9.4.1
  volumes:
    - /var/lib/postgresql
  container_name: postgres-db-data

gitrob:
  build: .
  command: ./start.sh
  ports:
    - "9393:9393"
  links:
    - db
  volumes:
    - .:/weft-gitrob
  container_name: gitrob